### ISSUE TITLE
Implement GitHub workflow for PRs

### ISSUE THREAD

**Issue by sebastian-j-ibanez** [ccosp/open-o#131]
## Changes to be made
- Create workflow yaml file.
  - Setup Java 1.8 
  - Run `make install`
- Workflow runs when PR targets the following branches:
  - master
  - magenta-master
  - develop/alpaca
  - develop/bullfrog

**Comment by yingbull** [comment]
Great work.  Can you test where we are just in terms of the repos building all the jsps on your own environment?  Not sure the path to take here but before we decide on workflow validation of jsp compiles lets make sure it works locally; that can be another ticket.

**Comment by yingbull** [comment]
Fine to get this into the alpaca branch as well since it is in a directory that doesn't affect the EMR itself.

Noticed that tests are off; if we leave them on, will it run the tests and fail if they fail? If so, let's turn that on.  I accepted the PR, but lets make that change if you test it and it works.
